apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demon
  namespace: namespacetest
  labels:
    app: test
spec:       
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        ports: 
        - containerPort: 80
