apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: namespacetest
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
