apiVersion: v1
kind: Pod
metadata: 
  name: test
  namespace: namespacetest
  labels:
    name: test
spec:
  containers:
  - name: test
    image: bitbull/webserver
    ports: 
    - containerPort: 80
    
    env:
    - name: FIRST_CONFIG
      valueFrom:
        configMapKeyRef:
          name: test-config
          key: Description
