apiVersion: v1
kind: Pod

metadata:
  name: pod-first
  namespace: namespacetest 
  labels:
    name: test
spec:
  containers:
  - name: test
    image: bitbull/webserver
    ports:
    - containerPort: 80    
