apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pv-state
  namespace: namespacetest
  labels:
    app: test
spec:
  serviceName: ""
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        volumeMounts:
        - name: stateful-vol
          mountPath: "/tmp/volume"
      volumes:
      - name: stateful-vol
        
        persistentVolumeClaim:
          claimName: sts-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sts-pvc
  namespace: namespacetest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
