apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-update
  namespace: namespacetest
  labels:
    app: test
spec:
  replicas: 3
  strategy:
    type: Recreate       # by default rollupdate strategy if not mentioned.
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: testing
        image: jenkins:2.60.3
