apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: namespacetest
data:
  username: cmV0dXJuCg==
  password: cmV0dXJuLTIK

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-first
  namespace: namespacetest
  labels:
    app: test
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test    
    spec:
      containers:
      - name: test
        image: bitbull/webserver
        ports:
        - containerPort: 80
        env:
        - name: user-abhi
          valueFrom:
            secretKeyRef:
              name: secret
              key:  username
