apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: state
  namespace: namespacetest
  labels:
    app: test
spec:
  serviceName: ""       
  replicas: 2 
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
